# Generated by Django 3.2.5 on 2021-07-19 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_alter_sample_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='part',
            table='part_application',
        ),
    ]
