# Generated by Django 3.2.4 on 2021-06-21 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SamplePart',
            new_name='Part',
        ),
        migrations.AlterModelTable(
            name='part',
            table='part',
        ),
    ]
