# Generated by Django 3.2.5 on 2021-07-19 16:51

import django.contrib.postgres.fields
from django.db import migrations, models
import genesis.analysis.model_data.parentData


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Sample name', max_length=200)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('filters', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(help_text='Filters', max_length=200), size=None)),
            ],
            options={
                'db_table': 'sample',
            },
            bases=(models.Model, genesis.analysis.model_data.parentData.DataModel),
        ),
    ]
