# Generated by Django 3.2.5 on 2021-07-26 07:35

from django.db import migrations, models
import django.db.models.deletion
import genesis.analysis.model_data.parentData


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmd', models.CharField(max_length=5000)),
                ('end_date', models.DateTimeField(auto_now_add=True)),
                ('software_version', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'gen_analysis',
            },
            bases=(models.Model, genesis.analysis.model_data.parentData.DataModel),
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquisition_date', models.DateTimeField(auto_now_add=True)),
                ('model', models.CharField(max_length=50)),
                ('provider_sn', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'gen_instrument',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'gen_provider',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('path', models.CharField(max_length=300)),
                ('tag', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='analysis.analysis')),
            ],
            options={
                'db_table': 'gen_result',
            },
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='analysis.instrument')),
            ],
            options={
                'db_table': 'gen_run',
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=300)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='analysis.sample')),
            ],
            options={
                'db_table': 'gen_sample',
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'gen_software',
            },
        ),
        migrations.CreateModel(
            name='SampleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=10)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='analysis.sample')),
            ],
            options={
                'db_table': 'gen_sample_tag',
            },
        ),
        migrations.CreateModel(
            name='SampleResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='analysis.result')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='analysis.sample')),
            ],
            options={
                'db_table': 'gen_sample_result',
            },
        ),
        migrations.CreateModel(
            name='RunTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=10)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='analysis.run')),
            ],
            options={
                'db_table': 'gen_run_tag',
            },
        ),
        migrations.CreateModel(
            name='RunSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='analysis.run')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='analysis.sample')),
            ],
            options={
                'db_table': 'gen_run_sample',
            },
        ),
        migrations.CreateModel(
            name='ResultConsumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='analysis.analysis')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='analysis.result')),
            ],
            options={
                'db_table': 'gen_result_consumer',
            },
        ),
        migrations.AddField(
            model_name='result',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='analysis.run'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='analysis.provider'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='software',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='analysis.software'),
        ),
    ]
