# Generated by Django 3.2.5 on 2021-07-26 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='cmd',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='software_version',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='acquisition_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='tag',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resultconsumer',
            name='consumer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='analysis.analysis'),
        ),
        migrations.AlterField(
            model_name='run',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='run',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='creation_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
