# Generated by Django 3.2.5 on 2021-07-22 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='samples',
        ),
        migrations.RemoveField(
            model_name='run',
            name='samples',
        ),
        migrations.CreateModel(
            name='SampleResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='analysis.result')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='analysis.sample')),
            ],
            options={
                'db_table': 'gen_sample_result',
            },
        ),
        migrations.CreateModel(
            name='RunSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='analysis.run')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='analysis.sample')),
            ],
            options={
                'db_table': 'gen_run_sample',
            },
        ),
    ]
