# Generated by Django 3.2.5 on 2021-07-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_auto_20210722_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='cmd',
            field=models.CharField(max_length=5000),
        ),
    ]
